export const MESSAGES = {
  USER_NOT_FOUND: 'User not found',
  EMAIL_IS_INVALID: 'Email is invalid',
  UNPROCESSABLE_ENTITY: 'Unprocessable Entity',
  EMAIL_ALREADY_EXISTS: 'Email already exitsts'
}
export const HTTP_STATUS = {
  UNAUTHORIZED: 401,
  UNPROCESSABLE_ENTITY: 422,
  NOT_FOUND: 404,
  FORBIDDEN: 403,
  BAD_REQUEST: 400,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  PRECONDITION_FAILED: 412,
  REQUEST_TIMEOUT: 408,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
}
